# Generated by Django 3.1.7 on 2021-03-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Active'), (1, 'Deactivated')], default=0, verbose_name='status')),
                ('title', models.CharField(max_length=255, verbose_name='Product title')),
                ('stock', models.IntegerField(default=0, verbose_name='number of stocks')),
                ('price', models.IntegerField(null=True, verbose_name='Price')),
                ('age', models.IntegerField(null=True, verbose_name='Age')),
            ],
        ),
    ]
